config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main1.urls", namespace="main1")),
    path('users/', include('users.urls', namespace='users'))
]

main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from main.apps import MainConfig
from main.views import ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView, \
    MessageListView, MessageDeleteView, MessageUpdateView, MessageCreateView, MessageDetailView, NewsletterCreateView, \
    NewsletterListView, NewsletterDetailView, NewsletterUpdateView, NewsletterDeleteView

app_name = MainConfig.name


urlpatterns = [
    path('', ClientListView.as_view(), name="client_list"),
    path('client_detail/<int:pk>', ClientDetailView.as_view(), name="client_detail"),
    path('client_create', ClientCreateView.as_view(), name="client_create"),
    path('client_update/<int:pk>', ClientUpdateView.as_view(), name="client_update"),
    path('client_delete/<int:pk>', ClientDeleteView.as_view(), name="client_delete"),

    path('message_list', MessageListView.as_view(), name="message_list"),
    path('message_detail/<int:pk>', MessageDetailView.as_view(), name="message_detail"),
    path('message_create', MessageCreateView.as_view(), name="message_create"),
    path('message_update/<int:pk>', MessageUpdateView.as_view(), name="message_update"),
    path('message_delete/<int:pk>', MessageDeleteView.as_view(), name="message_delete"),

    path('newsletter_list', NewsletterListView.as_view(), name="newsletter_list"),
    path('newsletter_detail/<int:pk>', NewsletterDetailView.as_view(), name="newsletter_detail"),
    path('newsletter_update/<int:pk>', NewsletterUpdateView.as_view(), name="newsletter_update"),
    path('newsletter_delete/<int:pk>', NewsletterDeleteView.as_view(), name="newsletter_delete"),
    path('newsletter_create', NewsletterCreateView.as_view(), name="newsletter_create"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from main1.apps import MainConfig
from main1.views import ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView, \
    MessageListView, MessageDeleteView, MessageUpdateView, MessageCreateView, MessageDetailView, NewsletterCreateView, \
    NewsletterListView, NewsletterDetailView, NewsletterUpdateView, NewsletterDeleteView, BlogPostCreateView, HomePage, \
    MailingAttemptLogListView

app_name = MainConfig.name


urlpatterns = [
    path('', HomePage.as_view(), name="home"),
    path('client_list', ClientListView.as_view(), name="client_list"),
    path('client_detail/<int:pk>', cache_page(60)(ClientDetailView.as_view()), name="client_detail"),
    path('client_create', ClientCreateView.as_view(), name="client_create"),
    path('client_update/<int:pk>', ClientUpdateView.as_view(), name="client_update"),
    path('client_delete/<int:pk>', ClientDeleteView.as_view(), name="client_delete"),

    path('message_list', MessageListView.as_view(), name="message_list"),
    path('message_detail/<int:pk>', cache_page(60)(MessageDetailView.as_view()), name="message_detail"),
    path('message_create', MessageCreateView.as_view(), name="message_create"),
    path('message_update/<int:pk>', MessageUpdateView.as_view(), name="message_update"),
    path('message_delete/<int:pk>', MessageDeleteView.as_view(), name="message_delete"),

    path('newsletter_list', NewsletterListView.as_view(), name="newsletter_list"),
    path('newsletter_detail/<int:pk>', NewsletterDetailView.as_view(), name="newsletter_detail"),
    path('newsletter_update/<int:pk>', NewsletterUpdateView.as_view(), name="newsletter_update"),
    path('newsletter_delete/<int:pk>', NewsletterDeleteView.as_view(), name="newsletter_delete"),
    path('newsletter_create', NewsletterCreateView.as_view(), name="newsletter_create"),

    path('blogpost_create', BlogPostCreateView.as_view(), name="blogpost_create"),

    path('log_list', MailingAttemptLogListView.as_view(), name="log_list")

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, password_reset, UserUpdateView, UserListView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path("email-confirm/<str:token>/", email_verification, name='email-confirm'),
    path("password_reset/", password_reset, name='password_reset'),
    path("user_update/<int:pk>", UserUpdateView.as_view(), name='user_update'),
    path("user_list/", UserListView.as_view(), name='users_list')

]

main1/forms.py
from django.forms import BooleanField, ModelForm

from main1.models import Client, Message, Newsletter


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fild_name, fild in self.fields.items():
            if isinstance(fild, BooleanField):
                fild.widget.attrs['class'] = 'form-check-input'
            else:
                fild.widget.attrs['class'] = 'form-control'


class ClientForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Client
        exclude = ("user_creator",)


class MessageForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Message
        exclude = ("created_at", "updated_at", "user_creator")


class NewsletterForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Newsletter
        exclude = ("user_creator", "created_at", "status")


class NewsletterManagerForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Newsletter
        fields = ("status",)

main1/views.py
import random

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, CreateView, TemplateView
from pytils.templatetags.pytils_translit import slugify

from main1.forms import ClientForm, MessageForm, NewsletterForm, NewsletterManagerForm
from main1.models import Client, Message, Newsletter, BlogPost, MailingAttemptLog


class ClientListView(ListView):
    model = Client


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.name)
            new_mat.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('main1:client_detail', args=[self.kwargs.get('pk')])


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('main1:client_list')

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.user_creator = user
        client.save()
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.name)
            new_mat.save()
        return super().form_valid(form)


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('main1:client_list')

# РАБОТА С СООБЩЕНИЯМИ __________________________________________________________________________


class MessageListView(ListView):
    model = Message


class MessageDetailView(DetailView):
    model = Message


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.name)
            new_mat.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('main1:message_detail', args=[self.kwargs.get('pk')])


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('main1:message_list')

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.user_creator = user
        client.save()
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.name)
            new_mat.save()
        return super().form_valid(form)


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('main1:client_list')


# РАБОТА С РАССЫЛКАМИ___________________________________


class NewsletterListView(ListView):
    model = Newsletter


class NewsletterDetailView(DetailView):
    model = Newsletter


class NewsletterUpdateView(LoginRequiredMixin, UpdateView):
    model = Newsletter
    # form_class = NewsletterForm

    def get_form_class(self):
        user = self.request.user
        if user.is_superuser or user == self.object.user_creator:
            return NewsletterForm
        elif user.groups.filter(name='Менеджер').exists():
            return NewsletterManagerForm
        raise PermissionDenied

    def get_success_url(self):
        return reverse('main1:newsletter_detail', args=[self.kwargs.get('pk')])


class NewsletterCreateView(LoginRequiredMixin, CreateView):
    model = Newsletter
    form_class = NewsletterForm
    success_url = reverse_lazy('main1:newsletter_list')

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.user_creator = user
        client.save()
        return super().form_valid(form)


class NewsletterDeleteView(LoginRequiredMixin, DeleteView):
    model = Newsletter
    success_url = reverse_lazy('main1:client_list')


# ______________________БЛОГ_______________________________________

class BlogPostCreateView(LoginRequiredMixin, CreateView):
    model = BlogPost
    fields = ('title', 'content', 'image', 'publication_sign')
    success_url = reverse_lazy('main1:home')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()
        return super().form_valid(form)


class BlogPostUpdateView(LoginRequiredMixin, UpdateView):
    model = BlogPost
    fields = ('title', 'content', 'image', 'publication_sign')
    success_url = reverse_lazy('main1:home')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('main1:blogpost_detail', args=[self.kwargs.get('pk')])


class BlogPostListView(ListView):
    model = BlogPost

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset()
        queryset = queryset.filter(publication_sign=True)
        return queryset


class BlogPostDetailView(DetailView):
    model = BlogPost

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class HomePage(TemplateView):
    template_name = "main1/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = BlogPost.objects.all()
        post_list = []
        for p in post:
            post_list.append(p)
        if len(post_list) < 3:
            post_list_sample = post_list
        else:
            post_list_sample = random.sample(post_list, 3)
        context['blogpost'] = post_list_sample

        newsletter = Newsletter.objects.all()
        context['newsletter_sum'] = len(newsletter)
        context['newsletter_activ'] = len(newsletter.filter(status="Запущена"))

        clients = Client.objects.all()
        clients_list = []
        for client in clients:
            clients_list.append(client.email)
        context['client_unique'] = len(set(clients_list))

        return context

# ____________________Попытка рассылки:_____________________


class MailingAttemptLogListView(LoginRequiredMixin, ListView):
    model = MailingAttemptLog

main1/templates/includes/inc_menu.html
<header data-bs-theme="dark">
    <div class="collapse text-bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4>РАССЫЛКИ</h4>
                    <p class="text-body-secondary">Сервис по рассылкам</p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4>МЕНЮ</h4>
                    <ul class="list-unstyled">
                        <li><a href="#" class="text-white">Контакты</a></li>
                        <li><a href="{% url 'main1:client_list'  %}" class="text-white">Cписок клиентов</a></li>

                        <li><a href="{% url 'main1:client_create'  %}" class="text-white">Добавить клиента</a></li>

                        {% if user.is_authenticated %}
                        <li><a href="{% url 'users:logout' %}" class="text-white">Выход</a></li>
                        <li><a href="{% url 'main1:log_list' %}" class="text-white">LOG</a></li>
                        {% else %}
                        <li><a href="{% url 'users:login' %}" class="text-white">Вход</a></li>
                        <li><a href="{% url 'users:register' %}" class="text-white">Регистрация</a></li>
                        <li><a href="{% url 'users:password_reset' %}" class="text-white">Востановить пароль</a></li>
                      {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
            <a href="{% url 'main1:home' %}" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                     stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2"
                     viewBox="0 0 24 24">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
                    <circle cx="12" cy="13" r="4"/>
                </svg>
                <strong>Главное окно</strong>
            </a>
            <a href="{% url 'main1:message_create' %}" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                     stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2"
                     viewBox="0 0 24 24">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
                    <circle cx="12" cy="13" r="4"/>
                </svg>
                <strong>Создать Сообщение</strong>
            </a>
            <a href="{% url 'main1:client_create' %}" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                     stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2"
                     viewBox="0 0 24 24">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
                    <circle cx="12" cy="13" r="4"/>
                </svg>
                <strong>Добавить клиента</strong>
            </a>
            <a href="{% url 'main1:newsletter_create' %}" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                     stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2"
                     viewBox="0 0 24 24">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
                    <circle cx="12" cy="13" r="4"/>
                </svg>
                <strong>Создать рассылку</strong>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>