config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main1.urls", namespace="main1")),
    path('users/', include('users.urls', namespace='users'))
]

main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from main.apps import MainConfig
from main.views import ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView, \
    MessageListView, MessageDeleteView, MessageUpdateView, MessageCreateView, MessageDetailView, NewsletterCreateView, \
    NewsletterListView, NewsletterDetailView, NewsletterUpdateView, NewsletterDeleteView

app_name = MainConfig.name


urlpatterns = [
    path('', ClientListView.as_view(), name="client_list"),
    path('client_detail/<int:pk>', ClientDetailView.as_view(), name="client_detail"),
    path('client_create', ClientCreateView.as_view(), name="client_create"),
    path('client_update/<int:pk>', ClientUpdateView.as_view(), name="client_update"),
    path('client_delete/<int:pk>', ClientDeleteView.as_view(), name="client_delete"),

    path('message_list', MessageListView.as_view(), name="message_list"),
    path('message_detail/<int:pk>', MessageDetailView.as_view(), name="message_detail"),
    path('message_create', MessageCreateView.as_view(), name="message_create"),
    path('message_update/<int:pk>', MessageUpdateView.as_view(), name="message_update"),
    path('message_delete/<int:pk>', MessageDeleteView.as_view(), name="message_delete"),

    path('newsletter_list', NewsletterListView.as_view(), name="newsletter_list"),
    path('newsletter_detail/<int:pk>', NewsletterDetailView.as_view(), name="newsletter_detail"),
    path('newsletter_update/<int:pk>', NewsletterUpdateView.as_view(), name="newsletter_update"),
    path('newsletter_delete/<int:pk>', NewsletterDeleteView.as_view(), name="newsletter_delete"),
    path('newsletter_create', NewsletterCreateView.as_view(), name="newsletter_create"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from main1.apps import MainConfig
from main1.views import ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView, \
    MessageListView, MessageDeleteView, MessageUpdateView, MessageCreateView, MessageDetailView, NewsletterCreateView, \
    NewsletterListView, NewsletterDetailView, NewsletterUpdateView, NewsletterDeleteView, BlogPostCreateView, HomePage, \
    MailingAttemptLogListView

app_name = MainConfig.name


urlpatterns = [
    path('', HomePage.as_view(), name="home"),
    path('client_list', ClientListView.as_view(), name="client_list"),
    path('client_detail/<int:pk>', cache_page(60)(ClientDetailView.as_view()), name="client_detail"),
    path('client_create', ClientCreateView.as_view(), name="client_create"),
    path('client_update/<int:pk>', ClientUpdateView.as_view(), name="client_update"),
    path('client_delete/<int:pk>', ClientDeleteView.as_view(), name="client_delete"),

    path('message_list', MessageListView.as_view(), name="message_list"),
    path('message_detail/<int:pk>', cache_page(60)(MessageDetailView.as_view()), name="message_detail"),
    path('message_create', MessageCreateView.as_view(), name="message_create"),
    path('message_update/<int:pk>', MessageUpdateView.as_view(), name="message_update"),
    path('message_delete/<int:pk>', MessageDeleteView.as_view(), name="message_delete"),

    path('newsletter_list', NewsletterListView.as_view(), name="newsletter_list"),
    path('newsletter_detail/<int:pk>', NewsletterDetailView.as_view(), name="newsletter_detail"),
    path('newsletter_update/<int:pk>', NewsletterUpdateView.as_view(), name="newsletter_update"),
    path('newsletter_delete/<int:pk>', NewsletterDeleteView.as_view(), name="newsletter_delete"),
    path('newsletter_create', NewsletterCreateView.as_view(), name="newsletter_create"),

    path('blogpost_create', BlogPostCreateView.as_view(), name="blogpost_create"),

    path('log_list', MailingAttemptLogListView.as_view(), name="log_list")

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, password_reset, UserUpdateView, UserListView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path("email-confirm/<str:token>/", email_verification, name='email-confirm'),
    path("password_reset/", password_reset, name='password_reset'),
    path("user_update/<int:pk>", UserUpdateView.as_view(), name='user_update'),
    path("user_list/", UserListView.as_view(), name='users_list')

]

main1/forms.py
from django.forms import BooleanField, ModelForm

from main1.models import Client, Message, Newsletter


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fild_name, fild in self.fields.items():
            if isinstance(fild, BooleanField):
                fild.widget.attrs['class'] = 'form-check-input'
            else:
                fild.widget.attrs['class'] = 'form-control'


class ClientForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Client
        exclude = ("user_creator",)


class MessageForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Message
        exclude = ("created_at", "updated_at", "user_creator")


class NewsletterForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Newsletter
        exclude = ("user_creator", "created_at", "status")


class NewsletterManagerForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Newsletter
        fields = ("status",)

main1/views.py
import random

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, CreateView, TemplateView
from pytils.templatetags.pytils_translit import slugify

from main1.forms import ClientForm, MessageForm, NewsletterForm, NewsletterManagerForm
from main1.models import Client, Message, Newsletter, BlogPost, MailingAttemptLog


class ClientListView(ListView):
    model = Client


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.name)
            new_mat.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('main1:client_detail', args=[self.kwargs.get('pk')])


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('main1:client_list')

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.user_creator = user
        client.save()
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.name)
            new_mat.save()
        return super().form_valid(form)


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('main1:client_list')

# РАБОТА С СООБЩЕНИЯМИ __________________________________________________________________________


class MessageListView(ListView):
    model = Message


class MessageDetailView(DetailView):
    model = Message


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.name)
            new_mat.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('main1:message_detail', args=[self.kwargs.get('pk')])


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('main1:message_list')

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.user_creator = user
        client.save()
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.name)
            new_mat.save()
        return super().form_valid(form)


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('main1:client_list')


# РАБОТА С РАССЫЛКАМИ___________________________________


class NewsletterListView(ListView):
    model = Newsletter


class NewsletterDetailView(DetailView):
    model = Newsletter


class NewsletterUpdateView(LoginRequiredMixin, UpdateView):
    model = Newsletter
    # form_class = NewsletterForm

    def get_form_class(self):
        user = self.request.user
        if user.is_superuser or user == self.object.user_creator:
            return NewsletterForm
        elif user.groups.filter(name='Менеджер').exists():
            return NewsletterManagerForm
        raise PermissionDenied

    def get_success_url(self):
        return reverse('main1:newsletter_detail', args=[self.kwargs.get('pk')])


class NewsletterCreateView(LoginRequiredMixin, CreateView):
    model = Newsletter
    form_class = NewsletterForm
    success_url = reverse_lazy('main1:newsletter_list')

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.user_creator = user
        client.save()
        return super().form_valid(form)


class NewsletterDeleteView(LoginRequiredMixin, DeleteView):
    model = Newsletter
    success_url = reverse_lazy('main1:client_list')


# ______________________БЛОГ_______________________________________

class BlogPostCreateView(LoginRequiredMixin, CreateView):
    model = BlogPost
    fields = ('title', 'content', 'image', 'publication_sign')
    success_url = reverse_lazy('main1:home')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()
        return super().form_valid(form)


class BlogPostUpdateView(LoginRequiredMixin, UpdateView):
    model = BlogPost
    fields = ('title', 'content', 'image', 'publication_sign')
    success_url = reverse_lazy('main1:home')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('main1:blogpost_detail', args=[self.kwargs.get('pk')])


class BlogPostListView(ListView):
    model = BlogPost

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset()
        queryset = queryset.filter(publication_sign=True)
        return queryset


class BlogPostDetailView(DetailView):
    model = BlogPost

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class HomePage(TemplateView):
    template_name = "main1/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = BlogPost.objects.all()
        post_list = []
        for p in post:
            post_list.append(p)
        if len(post_list) < 3:
            post_list_sample = post_list
        else:
            post_list_sample = random.sample(post_list, 3)
        context['blogpost'] = post_list_sample

        newsletter = Newsletter.objects.all()
        context['newsletter_sum'] = len(newsletter)
        context['newsletter_activ'] = len(newsletter.filter(status="Запущена"))

        clients = Client.objects.all()
        clients_list = []
        for client in clients:
            clients_list.append(client.email)
        context['client_unique'] = len(set(clients_list))

        return context

# ____________________Попытка рассылки:_____________________


class MailingAttemptLogListView(LoginRequiredMixin, ListView):
    model = MailingAttemptLog

main1/templates/main1/blogpost_form.html
{% extends 'main1/index.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Сервис Рассылки</h1>
    <h2 class="display-4">Добавление ПОСТ</h2>
</div>

<div class="coll-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                        <a class="btn btn-danger" href="{% url 'main1:home' %}"
                           role="button">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main1/templates/main1/client_confirm_delete.html
{% extends 'main1/index.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Сервис Рассылки</h1>

</div>

<div class="coll-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <p>Хотите удалить Клиента {{ client.name }}</p>
                        <button type="submit" class="btn btn-danger">Удалить</button>
                        <a class="btn btn-primary" href="{% url 'main1:client_list' %}" role="button">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main1/templates/main1/client_list.html
{% extends 'main1/index.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Рассылки</h1>
    <h2 class="display-4">КЛИЕНТЫ</h2>
</div>
<div class="container">
    <div class="row text-center">
        {% for client in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ client.name }}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ client.email }}</h1>
<!--                    <img src="{{ prod.image_product | media_filter}}" class="img-thumbnail">-->
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{{ client.comment | truncatechars:10 }}</li>
                    </ul>
                    <a class="btn btn-primary" href="{% url 'main1:client_detail' client.pk %}"
                       role="button">Подробно</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endblock %}

main1/templates/main1/home.html
{% extends 'main1/index.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Рассылки</h1>
    <h2 class="display-4">Главная страница</h2>
</div>
<div class="card-body">
    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
        <li>Количество рассылок - {{ newsletter_sum }}</li>
        <li>Количество активных рассылок - {{ newsletter_activ }}</li>
        <li>Количество уникальных пользователей - {{ client_unique }}</li>

    </ul>
</div>
<div class="container">
    <div class="row text-center">
        {% for post in blogpost %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ post.title }}</h4>
                </div>
                <div class="card-body">
                    <img src="{{ blogpost.image | media_filter}}" class="img-thumbnail">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{{ post.created_at }}</li>
                        <li>{{ post.content | truncatechars:10 }}</li>
                    </ul>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endblock %}

main1/templates/main1/index.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>РАССЫЛКИ</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
          crossorigin="anonymous">

        <!-- Bootstrap core CSS -->
    <link href="/static/bootstrap.min.css" rel="stylesheet">

</head>
<body>
{% include 'includes/inc_menu.html' %}

{% block content %}
{% endblock %}

     <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">

                <small class="d-block mb-3 text-muted">&copy; 2024</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'main1:message_list' %}">Все созданные сообщения</a></li>
                    <li><a class="text-muted" href="{% url 'main1:newsletter_list' %}">Все созданные рассылки</a></li>
                    {% if user.is_superuser or perms.main1.set_is_activ_user %}
                    <li><a class="text-muted" href="{% url 'users:users_list' %}">Все пользоатели</a></li>
                    <li><a class="text-muted" href="{% url 'main1:blogpost_create' %}">Добавить пост</a></li>
                    {% endif %}
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="/static/popper.min.js"></script>

</body>
</html>

main1/templates/main1/mailingattemptlog_list.html
{% extends 'main1/index.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Рассылки</h1>
    <h2 class="display-4">LOG</h2>
</div>
<div class="container">
    <div class="row text-center">
        {% for log in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ log.status }}</h4>
                </div>
                <div class="card-body">
                    <h4 class="card-title pricing-card-title">{{ log.time }}</h4>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{{ log.server_response }}</li>
                    </ul>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endblock %}

main1/templates/main1/message_confirm_delete.html
{% extends 'main1/index.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Сервис Рассылки</h1>

</div>

<div class="coll-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <p>Хотите удалить Сообщение {{ message.name }}</p>
                        <button type="submit" class="btn btn-danger">Удалить</button>
                        <a class="btn btn-primary" href="{% url 'main1:client_list' %}" role="button">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main1/templates/main1/message_detail.html
{% extends 'main1/index.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Сервис Рассылки</h1>
    <h2 class="display-4">Информация о сообщении</h2>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>Текст - {{ object.text }}</li>
                        <li>Дата создания - {{ object.created_at }}</li>
                        <li>Создал - {{ object.user_creator }}</li>

                    </ul>
                    <a class="btn btn-primary" href="{% url 'main1:client_list' %}" role="button">Назад</a>
                    {% if perms.user.is_superuser %}
                    <a class="btn btn-primary" href="{% url 'main1:message_update' message.pk %}" role="button">Редактировать</a>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>
    {% endblock %}

main1/templates/main1/message_form.html
{% extends 'main1/index.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Сервис Рассылки</h1>
    <h2 class="display-4">Создание сообщений</h2>
</div>

<div class="coll-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                        <a class="btn btn-danger" href="{% url 'main1:client_list' %}"
                           role="button">Отмена</a>
                        {% if perms.user.is_superuser and message.pk%}
                            <a class="btn btn-danger" href="{% url 'main1:message_delete' message.pk %}" role="button">Удалить</a>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main1/templates/main1/message_list.html
{% extends 'main1/index.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h2 class="display-4">Созданные сообщения</h2>
</div>
<div class="container">
    <div class="row text-center">
        {% for message in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ message.name }}</h4>
                </div>
                <div class="card-body">
                    <h4 class="card-title pricing-card-title">Дата создания {{ message.created_at }}</h4>
<!--                    <img src="{{ prod.image_product | media_filter}}" class="img-thumbnail">-->
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{{ message.text | truncatechars:20 }}</li>
                    </ul>
                    <a class="btn btn-primary" href="{% url 'main1:message_detail' message.pk %}"
                       role="button">Подробно</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endblock %}

main1/templates/main1/newsletter_confirm_delete.html
{% extends 'main1/index.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Сервис Рассылки</h1>

</div>

<div class="coll-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <p>Хотите удалить Рассылку {{ newsletter.pk }}</p>
                        <button type="submit" class="btn btn-danger">Удалить</button>
                        <a class="btn btn-primary" href="{% url 'main1:client_list' %}" role="button">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main1/templates/main1/newsletter_detail.html
{% extends 'main1/index.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Сервис Рассылки</h1>
    <h2 class="display-4">Информация о расылке</h2>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.status }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>дата и время первой отправки {{ object.date_time_go }}</li>
                        <li>Дата создания - {{ object.created_at }}</li>
                        <li>Создал - {{ object.user_creator }}</li>
                        <li>Период - {{ object.period }}</li>
                        <li>Кому -
                         {% for client in object.client.all %}
                            <p class="card-text"> {{ client.name }},  {{client.email}}</p></li>
                          {% endfor %}
                        <li>Сообщение -
                            {% for massage in object.massage.all %}
                            <p class="card-text"> {{ massage.name }}</p></li>
                          {% endfor %}</li>

                    </ul>
                    <a class="btn btn-primary" href="{% url 'main1:newsletter_list' %}" role="button">Назад</a>
                    {% if user.is_superuser or perms.main1.set_is_activ_user %}
                    <a class="btn btn-primary" href="{% url 'main1:newsletter_update' newsletter.pk %}" role="button">Редактировать</a>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>
    {% endblock %}

main1/templates/main1/newsletter_form.html
{% extends 'main1/index.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Сервис Рассылки</h1>
    <h2 class="display-4">Создание РАССЫЛКИ</h2>
</div>

<div class="coll-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                        <a class="btn btn-danger" href="{% url 'main1:client_list' %}"
                           role="button">Отмена</a>
                        {% if perms.user.is_superuser and newsletter.pk%}
                            <a class="btn btn-danger" href="{% url 'main1:newsletter_delete' newsletter.pk %}" role="button">Удалить</a>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main1/templates/main1/newsletter_list.html
{% extends 'main1/index.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h2 class="display-4">Созданные рассылки</h2>
</div>
<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.period }}</h4>
                </div>
                <div class="card-body">
                    <h4 class="card-title pricing-card-title">Дата создания {{ object.created_at }}</h4>
<!--                    <img src="{{ prod.image_product | media_filter}}" class="img-thumbnail">-->
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>Статус {{ object.status }}</li>
                        <li>Дата отправки {{ object.date_time_go }}</li>
                    </ul>
                    <a class="btn btn-primary" href="{% url 'main1:newsletter_detail' object.pk %}"
                       role="button">Подробно</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endblock %}