config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main1.urls", namespace="main1")),
    path('users/', include('users.urls', namespace='users'))
]

main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from main.apps import MainConfig
from main.views import ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView, \
    MessageListView, MessageDeleteView, MessageUpdateView, MessageCreateView, MessageDetailView, NewsletterCreateView, \
    NewsletterListView, NewsletterDetailView, NewsletterUpdateView, NewsletterDeleteView

app_name = MainConfig.name


urlpatterns = [
    path('', ClientListView.as_view(), name="client_list"),
    path('client_detail/<int:pk>', ClientDetailView.as_view(), name="client_detail"),
    path('client_create', ClientCreateView.as_view(), name="client_create"),
    path('client_update/<int:pk>', ClientUpdateView.as_view(), name="client_update"),
    path('client_delete/<int:pk>', ClientDeleteView.as_view(), name="client_delete"),

    path('message_list', MessageListView.as_view(), name="message_list"),
    path('message_detail/<int:pk>', MessageDetailView.as_view(), name="message_detail"),
    path('message_create', MessageCreateView.as_view(), name="message_create"),
    path('message_update/<int:pk>', MessageUpdateView.as_view(), name="message_update"),
    path('message_delete/<int:pk>', MessageDeleteView.as_view(), name="message_delete"),

    path('newsletter_list', NewsletterListView.as_view(), name="newsletter_list"),
    path('newsletter_detail/<int:pk>', NewsletterDetailView.as_view(), name="newsletter_detail"),
    path('newsletter_update/<int:pk>', NewsletterUpdateView.as_view(), name="newsletter_update"),
    path('newsletter_delete/<int:pk>', NewsletterDeleteView.as_view(), name="newsletter_delete"),
    path('newsletter_create', NewsletterCreateView.as_view(), name="newsletter_create"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models

from users.models import Users


class Client(models.Model):
    email = models.EmailField(max_length=100, verbose_name="Почта клиента", help_text="Введите почту отправки сообщений")
    name = models.CharField(max_length=150, verbose_name="Ф.И.О", help_text="Введите Ф.И.О клиента")
    comment = models.TextField(verbose_name="комментарий", help_text="Введите комментарий к клиенту")
    created_at = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True)
    updated_at = models.DateField(verbose_name='Дата последнего изменения', auto_now=True)

    user_creator = models.ForeignKey(Users, verbose_name="Пользователь который создал продукт",
                                     help_text='Укажите пользователя который создал продукт',
                                     on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'{self.name} {self.email}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'
        ordering = ['created_at']


class Message(models.Model):
    name = models.CharField(max_length=200, verbose_name="тема письма", help_text="Введите тему письма")
    text = models.TextField(verbose_name="тело письма.", help_text="Введите сообщение клиенту")
    created_at = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True)
    updated_at = models.DateField(verbose_name='Дата последнего изменения', auto_now=True)
    user_creator = models.ForeignKey(Users, verbose_name="Пользователь который создал сообщение",
                                     help_text='Укажите пользователя который создал сообщение',
                                     on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Собщение'
        verbose_name_plural = 'Сообщения'
        ordering = ['created_at']


class Newsletter(models.Model):
    periods = (
        ("ЕЖЕДНЕВНО", "раз в день"),
        ("ЕЖЕНЕДЕЛЬНО", "раз в неделю"),
        ("Ежемесячно", "раз в месяц")
    )
    status_newsletter = (
        ("завершена", "завершена"),
        ("создана", "создана"),
        ("запущена", "запущена")
    )

    date_time_go = models.DateField(verbose_name="дата и время первой отправки рассылки",
                                        help_text="Введите дату и время первой отправки рассылки")
    period = models.CharField(max_length=100, verbose_name="периодичность", help_text="выберите периодичность",
                              choices=periods)
    status = models.CharField(max_length=100, verbose_name="статус рассылки",
                              choices=status_newsletter, default="создана")
    massage = models.ManyToManyField(Message, verbose_name="Сообщение",
                                     help_text='Выберите сообщение для отправки')
    client = models.ManyToManyField(Client, verbose_name="Клиент для отправки",
                                    help_text='Выберите клиента кому отправить')
    user_creator = models.ForeignKey(Users, verbose_name="Пользователь который создал рассылку",
                                     help_text='Укажите пользователя который создал рассылку',
                                     on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True, null=True)

    def __str__(self):
        return f'Отправленно клиенту {self.client}, статус {self.status}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        ordering = ['created_at']

main/forms.py
from django.forms import BooleanField, ModelForm

from main.models import Client, Message, Newsletter


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fild_name, fild in self.fields.items():
            if isinstance(fild, BooleanField):
                fild.widget.attrs['class'] = 'form-check-input'
            else:
                fild.widget.attrs['class'] = 'form-control'


class ClientForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Client
        exclude = ("user_creator",)


class MessageForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Message
        exclude = ("created_at", "updated_at", "user_creator")


class NewsletterForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Newsletter
        exclude = ("status", "user_creator", "created_at")

main/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, CreateView
from pytils.templatetags.pytils_translit import slugify

from main.forms import ClientForm, MessageForm, NewsletterForm
from main.models import Client, Message, Newsletter


class ClientListView(ListView):
    model = Client


class ClientDetailView(DetailView):
    model = Client


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.name)
            new_mat.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('main:client_detail', args=[self.kwargs.get('pk')])


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('main:client_list')

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.user_creator = user
        client.save()
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.name)
            new_mat.save()
        return super().form_valid(form)


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('main:client_list')

# РАБОТА С СООБЩЕНИЯМИ __________________________________________________________________________


class MessageListView(ListView):
    model = Message


class MessageDetailView(DetailView):
    model = Message


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.name)
            new_mat.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('main:message_detail', args=[self.kwargs.get('pk')])


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('main:client_list')

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.user_creator = user
        client.save()
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.name)
            new_mat.save()
        return super().form_valid(form)


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('main:client_list')


# РАБОТА С РАССЫЛКАМИ___________________________________


class NewsletterListView(ListView):
    model = Newsletter


class NewsletterDetailView(DetailView):
    model = Newsletter


class NewsletterUpdateView(LoginRequiredMixin, UpdateView):
    model = Newsletter
    form_class = NewsletterForm

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.name)
            new_mat.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('main:message_detail', args=[self.kwargs.get('pk')])


class NewsletterCreateView(LoginRequiredMixin, CreateView):
    model = Newsletter
    form_class = NewsletterForm
    success_url = reverse_lazy('main:client_list')

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.user_creator = user
        client.save()
        return super().form_valid(form)


class NewsletterDeleteView(LoginRequiredMixin, DeleteView):
    model = Newsletter
    success_url = reverse_lazy('main:client_list')

main/templates/includes/inc_menu.html
<header data-bs-theme="dark">
    <div class="collapse text-bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4>РАССЫЛКИ</h4>
                    <p class="text-body-secondary">Сервис по рассылкам</p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4>МЕНЮ</h4>
                    <ul class="list-unstyled">
                        <li><a href="#" class="text-white">Контакты</a></li>
                        <li><a href="#" class="text-white">Главное меню</a></li>
                        <li><a href="#" class="text-white">Блог активные</a></li>
                        <li><a href="#" class="text-white">Добавить блог</a></li>
                        <li><a href="#" class="text-white">Категории</a></li>
<!--                        {% if perms.catalog.add_product%}-->
                        <li><a href="{% url 'main:client_create'  %}" class="text-white">Добавить клиента</a></li>
                         {% endif %}
                        {% if user.is_authenticated %}
                        <li><a href="#" class="text-white">Выход</a></li>
                        {% else %}
                        <li><a href="#" class="text-white">Вход</a></li>
                        <li><a href="#" class="text-white">Регистрация</a></li>
                        <li><a href="#" class="text-white">Востановить пароль</a></li>
                      {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
            <a href="{% url 'main:client_list' %}" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                     stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2"
                     viewBox="0 0 24 24">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
                    <circle cx="12" cy="13" r="4"/>
                </svg>
                <strong>Главное окно</strong>
            </a>
            <a href="{% url 'main:message_create' %}" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                     stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2"
                     viewBox="0 0 24 24">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
                    <circle cx="12" cy="13" r="4"/>
                </svg>
                <strong>Создать Сообщение</strong>
            </a>
            <a href="{% url 'main:client_create' %}" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                     stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2"
                     viewBox="0 0 24 24">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
                    <circle cx="12" cy="13" r="4"/>
                </svg>
                <strong>Добавить клиента</strong>
            </a>
            <a href="{% url 'main:newsletter_create' %}" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                     stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2"
                     viewBox="0 0 24 24">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
                    <circle cx="12" cy="13" r="4"/>
                </svg>
                <strong>Создать рассылку</strong>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>