config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main1.urls", namespace="main1")),
    path('users/', include('users.urls', namespace='users'))
]

main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from main.apps import MainConfig
from main.views import ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView, \
    MessageListView, MessageDeleteView, MessageUpdateView, MessageCreateView, MessageDetailView, NewsletterCreateView, \
    NewsletterListView, NewsletterDetailView, NewsletterUpdateView, NewsletterDeleteView

app_name = MainConfig.name


urlpatterns = [
    path('', ClientListView.as_view(), name="client_list"),
    path('client_detail/<int:pk>', ClientDetailView.as_view(), name="client_detail"),
    path('client_create', ClientCreateView.as_view(), name="client_create"),
    path('client_update/<int:pk>', ClientUpdateView.as_view(), name="client_update"),
    path('client_delete/<int:pk>', ClientDeleteView.as_view(), name="client_delete"),

    path('message_list', MessageListView.as_view(), name="message_list"),
    path('message_detail/<int:pk>', MessageDetailView.as_view(), name="message_detail"),
    path('message_create', MessageCreateView.as_view(), name="message_create"),
    path('message_update/<int:pk>', MessageUpdateView.as_view(), name="message_update"),
    path('message_delete/<int:pk>', MessageDeleteView.as_view(), name="message_delete"),

    path('newsletter_list', NewsletterListView.as_view(), name="newsletter_list"),
    path('newsletter_detail/<int:pk>', NewsletterDetailView.as_view(), name="newsletter_detail"),
    path('newsletter_update/<int:pk>', NewsletterUpdateView.as_view(), name="newsletter_update"),
    path('newsletter_delete/<int:pk>', NewsletterDeleteView.as_view(), name="newsletter_delete"),
    path('newsletter_create', NewsletterCreateView.as_view(), name="newsletter_create"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models

from users.models import Users


class Client(models.Model):
    email = models.EmailField(max_length=100, verbose_name="Почта клиента", help_text="Введите почту отправки сообщений")
    name = models.CharField(max_length=150, verbose_name="Ф.И.О", help_text="Введите Ф.И.О клиента")
    comment = models.TextField(verbose_name="комментарий", help_text="Введите комментарий к клиенту")
    created_at = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True)
    updated_at = models.DateField(verbose_name='Дата последнего изменения', auto_now=True)

    user_creator = models.ForeignKey(Users, verbose_name="Пользователь который создал продукт",
                                     help_text='Укажите пользователя который создал продукт',
                                     on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'{self.name} {self.email}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'
        ordering = ['created_at']


class Message(models.Model):
    name = models.CharField(max_length=200, verbose_name="тема письма", help_text="Введите тему письма")
    text = models.TextField(verbose_name="тело письма.", help_text="Введите сообщение клиенту")
    created_at = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True)
    updated_at = models.DateField(verbose_name='Дата последнего изменения', auto_now=True)
    user_creator = models.ForeignKey(Users, verbose_name="Пользователь который создал сообщение",
                                     help_text='Укажите пользователя который создал сообщение',
                                     on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Собщение'
        verbose_name_plural = 'Сообщения'
        ordering = ['created_at']


class Newsletter(models.Model):
    periods = (
        ("ЕЖЕДНЕВНО", "раз в день"),
        ("ЕЖЕНЕДЕЛЬНО", "раз в неделю"),
        ("Ежемесячно", "раз в месяц")
    )
    status_newsletter = (
        ("завершена", "завершена"),
        ("создана", "создана"),
        ("запущена", "запущена")
    )

    date_time_go = models.DateField(verbose_name="дата и время первой отправки рассылки",
                                        help_text="Введите дату и время первой отправки рассылки")
    period = models.CharField(max_length=100, verbose_name="периодичность", help_text="выберите периодичность",
                              choices=periods)
    status = models.CharField(max_length=100, verbose_name="статус рассылки",
                              choices=status_newsletter, default="создана")
    massage = models.ManyToManyField(Message, verbose_name="Сообщение",
                                     help_text='Выберите сообщение для отправки')
    client = models.ManyToManyField(Client, verbose_name="Клиент для отправки",
                                    help_text='Выберите клиента кому отправить')
    user_creator = models.ForeignKey(Users, verbose_name="Пользователь который создал рассылку",
                                     help_text='Укажите пользователя который создал рассылку',
                                     on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True, null=True)

    def __str__(self):
        return f'Отправленно клиенту {self.client}, статус {self.status}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        ordering = ['created_at']

main/forms.py
from django.forms import BooleanField, ModelForm

from main.models import Client, Message, Newsletter


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fild_name, fild in self.fields.items():
            if isinstance(fild, BooleanField):
                fild.widget.attrs['class'] = 'form-check-input'
            else:
                fild.widget.attrs['class'] = 'form-control'


class ClientForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Client
        exclude = ("user_creator",)


class MessageForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Message
        exclude = ("created_at", "updated_at", "user_creator")


class NewsletterForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Newsletter
        exclude = ("status", "user_creator", "created_at")

main/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, CreateView
from pytils.templatetags.pytils_translit import slugify

from main.forms import ClientForm, MessageForm, NewsletterForm
from main.models import Client, Message, Newsletter


class ClientListView(ListView):
    model = Client


class ClientDetailView(DetailView):
    model = Client


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.name)
            new_mat.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('main:client_detail', args=[self.kwargs.get('pk')])


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('main:client_list')

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.user_creator = user
        client.save()
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.name)
            new_mat.save()
        return super().form_valid(form)


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('main:client_list')

# РАБОТА С СООБЩЕНИЯМИ __________________________________________________________________________


class MessageListView(ListView):
    model = Message


class MessageDetailView(DetailView):
    model = Message


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.name)
            new_mat.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('main:message_detail', args=[self.kwargs.get('pk')])


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('main:client_list')

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.user_creator = user
        client.save()
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.name)
            new_mat.save()
        return super().form_valid(form)


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('main:client_list')


# РАБОТА С РАССЫЛКАМИ___________________________________


class NewsletterListView(ListView):
    model = Newsletter


class NewsletterDetailView(DetailView):
    model = Newsletter


class NewsletterUpdateView(LoginRequiredMixin, UpdateView):
    model = Newsletter
    form_class = NewsletterForm

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.name)
            new_mat.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('main:message_detail', args=[self.kwargs.get('pk')])


class NewsletterCreateView(LoginRequiredMixin, CreateView):
    model = Newsletter
    form_class = NewsletterForm
    success_url = reverse_lazy('main:client_list')

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.user_creator = user
        client.save()
        return super().form_valid(form)


class NewsletterDeleteView(LoginRequiredMixin, DeleteView):
    model = Newsletter
    success_url = reverse_lazy('main:client_list')

main/templates/main/client_confirm_delete.html
{% extends 'main/index.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Сервис Рассылки</h1>

</div>

<div class="coll-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <p>Хотите удалить Клиента {{ client.name }}</p>
                        <button type="submit" class="btn btn-danger">Удалить</button>
                        <a class="btn btn-primary" href="{% url 'main:client_list' %}" role="button">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/client_detail.html
{% extends 'main/index.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Сервис Рассылки</h1>
    <h2 class="display-4">Информация о клиенте</h2>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>E-MAIL - {{ object.email }} </li>
                        <li>ОПИСАНИЕ - {{ object.comment }}</li>
                        <li>Создал - {{ object.user_creator }}</li>

                    </ul>
                    <a class="btn btn-primary" href="{% url 'main:client_list' %}" role="button">Назад</a>
                    {% if user == object.user_creator or perms.user.is_superuser %}
                    <a class="btn btn-primary" href="{% url 'main:client_update' client.pk %}" role="button">Редактировать</a>
                    {% endif %}

                </div>
            </div>
        </div>

    </div>
    {% endblock %}

main/templates/main/client_form.html
{% extends 'main/index.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Сервис Рассылки</h1>
    <h2 class="display-4">Добавление клинта</h2>
</div>

<div class="coll-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                        <a class="btn btn-danger" href="{% url 'main:client_list' %}"
                           role="button">Отмена</a>
                        {% if client.pk and perms.user.is_superuser%}
                            <a class="btn btn-danger" href="{% url 'main:client_delete' client.pk %}" role="button">Удалить</a>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/client_list.html
{% extends 'main/index.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
<!--    <h1 class="display-4">Магазин Шестерочка</h1>-->
<!--    <h2 class="display-4">Продукты</h2>-->
</div>
<div class="container">
    <div class="row text-center">
        {% for client in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ client.name }}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ client.email }}</h1>
<!--                    <img src="{{ prod.image_product | media_filter}}" class="img-thumbnail">-->
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{{ client.comment | truncatechars:10 }}</li>
                    </ul>
                    <a class="btn btn-primary" href="{% url 'main:client_detail' client.pk %}"
                       role="button">Подробно</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endblock %}

main/templates/main/index.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>РАССЫЛКИ</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
          crossorigin="anonymous">

        <!-- Bootstrap core CSS -->
    <link href="/static/bootstrap.min.css" rel="stylesheet">

</head>
<body>
{% include 'includes/inc_menu.html' %}

{% block content %}
{% endblock %}

     <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">

                <small class="d-block mb-3 text-muted">&copy; 2024</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'main:message_list' %}">Все созданные сообщения</a></li>
                    <li><a class="text-muted" href="{% url 'main:newsletter_list' %}">Все созданные рассылки</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="/static/popper.min.js"></script>

</body>
</html>

main/templates/main/message_confirm_delete.html
{% extends 'main/index.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Сервис Рассылки</h1>

</div>

<div class="coll-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <p>Хотите удалить Сообщение {{ message.name }}</p>
                        <button type="submit" class="btn btn-danger">Удалить</button>
                        <a class="btn btn-primary" href="{% url 'main:client_list' %}" role="button">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/message_detail.html
{% extends 'main/index.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Сервис Рассылки</h1>
    <h2 class="display-4">Информация о сообщении</h2>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>Текст - {{ object.text }}</li>
                        <li>Дата создания - {{ object.created_at }}</li>
                        <li>Создал - {{ object.user_creator }}</li>

                    </ul>
                    <a class="btn btn-primary" href="{% url 'main:client_list' %}" role="button">Назад</a>
                    {% if perms.user.is_superuser %}
                    <a class="btn btn-primary" href="{% url 'main:message_update' message.pk %}" role="button">Редактировать</a>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>
    {% endblock %}

main/templates/main/message_form.html
{% extends 'main/index.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Сервис Рассылки</h1>
    <h2 class="display-4">Создание сообщений</h2>
</div>

<div class="coll-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                        <a class="btn btn-danger" href="{% url 'main:client_list' %}"
                           role="button">Отмена</a>
                        {% if perms.user.is_superuser and message.pk%}
                            <a class="btn btn-danger" href="{% url 'main:message_delete' message.pk %}" role="button">Удалить</a>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/message_list.html
{% extends 'main/index.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h2 class="display-4">Созданные сообщения</h2>
</div>
<div class="container">
    <div class="row text-center">
        {% for message in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ message.name }}</h4>
                </div>
                <div class="card-body">
                    <h4 class="card-title pricing-card-title">Дата создания {{ message.created_at }}</h4>
<!--                    <img src="{{ prod.image_product | media_filter}}" class="img-thumbnail">-->
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{{ message.text | truncatechars:20 }}</li>
                    </ul>
                    <a class="btn btn-primary" href="{% url 'main:message_detail' message.pk %}"
                       role="button">Подробно</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endblock %}

main/templates/main/newsletter_confirm_delete.html
{% extends 'main/index.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Сервис Рассылки</h1>

</div>

<div class="coll-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <p>Хотите удалить Рассылку {{ newsletter.pk }}</p>
                        <button type="submit" class="btn btn-danger">Удалить</button>
                        <a class="btn btn-primary" href="{% url 'main:client_list' %}" role="button">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/newsletter_detail.html
{% extends 'main/index.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Сервис Рассылки</h1>
    <h2 class="display-4">Информация о расылке</h2>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.status }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>дата и время первой отправки {{ object.date_time_go }}</li>
                        <li>Дата создания - {{ object.created_at }}</li>
                        <li>Создал - {{ object.user_creator }}</li>
                        <li>Период - {{ object.period }}</li>
                        <li>Кому - {{ object.client }}</li>
                        <li>Сообщение - {{ object.massage }}</li>

                    </ul>
                    <a class="btn btn-primary" href="{% url 'main:client_list' %}" role="button">Назад</a>
                    {% if perms.user.is_superuser %}
                    <a class="btn btn-primary" href="{% url 'main:newsletter_update' newsletter.pk %}" role="button">Редактировать</a>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>
    {% endblock %}

main/templates/main/newsletter_form.html
{% extends 'main/index.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Сервис Рассылки</h1>
    <h2 class="display-4">Создание РАССЫЛКИ</h2>
</div>

<div class="coll-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                        <a class="btn btn-danger" href="{% url 'main:client_list' %}"
                           role="button">Отмена</a>
                        {% if perms.user.is_superuser and newsletter.pk%}
                            <a class="btn btn-danger" href="{% url 'main:newsletter_delete' newsletter.pk %}" role="button">Удалить</a>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/newsletter_list.html
{% extends 'main/index.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h2 class="display-4">Созданные рассылки</h2>
</div>
<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.period }}</h4>
                </div>
                <div class="card-body">
                    <h4 class="card-title pricing-card-title">Дата создания {{ object.created_at }}</h4>
<!--                    <img src="{{ prod.image_product | media_filter}}" class="img-thumbnail">-->
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>Статус {{ object.status }}</li>
                        <li>Дата отправки {{ object.date_time_go }}</li>
                    </ul>
                    <a class="btn btn-primary" href="{% url 'main:newsletter_detail' object.pk %}"
                       role="button">Подробно</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endblock %}